name: Sync Private Repos Issues

on:
  schedule:
    - cron: "*/2 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install axios fs-extra

      - name: Run Sync Script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          OWNER: zaki746
          REPOS: repo1,repo2
        run: node scripts/sync.js

      - name: Commit & Push if Changed
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add data/
          if ! git diff --cached --quiet; then
            git commit -m "Auto-update issues data"
            git push
          else
            echo "No changes."